#!/bin/bash

export PATH=/usr/local/bin:$PATH

eval "$(nubis-metadata)"

region=$(nubis-region)
instance_id=$(curl -s -fq http://169.254.169.254/latest/meta-data/instance-id)

eip_id=$(consul-cli kv read "${NUBIS_PROJECT}-${NUBIS_ENVIRONMENT}/${NUBIS_ENVIRONMENT}/config/ElasticIP")

aws --region "$region" ec2 associate-address --instance-id "$instance_id" --allocation-id "$eip_id"
